Repository Select-IOS-Team/ToDoListCleanSwift, pull requests merged in 2023-03, with the labels that each got.

#10 Тесты для моделей задач
  Tests/ImportantTaskTests.swift
  Tests/RegularTaskTests.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/TasksScene/BL/Task.swift
  ToDoListCleanSwift/TasksScene/BL/TaskManager.swift
  ToDoListCleanSwift/TasksScene/Managers/OrderedTaskManager.swift
Labels: enhancement

#6 Добавлены правила и gitignor
  .gitignore
  RULES.md
  ToDoListCleanSwift.xcodeproj/project.pbxproj
Labels: documentation

#11 Main.storyboard
  ToDoListCleanSwift/Base.lproj/Main.storyboard
Labels: bug

#12 Добавление теста для TaskManager
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/TasksScene/BL/Task.swift
  ToDoListCleanSwiftTests/Managers/TaskManagerTests.swift
  ToDoListCleanSwiftTests/Tasks/ImportantTaskTests.swift
  ToDoListCleanSwiftTests/Tasks/RegularTaskTests.swift
Labels: enhancement

#14 Исправление кодстайла в соответствии с правилами линтера
  ToDoListCleanSwift/AppDelegate.swift
  ToDoListCleanSwift/LoginScene/LoginInteractor.swift
  ToDoListCleanSwift/LoginScene/LoginModels.swift
  ToDoListCleanSwift/LoginScene/LoginPresenter.swift
  ToDoListCleanSwift/LoginScene/LoginViewController.swift
  ToDoListCleanSwift/LoginScene/LoginWorker.swift
  ToDoListCleanSwift/MainRouter.swift
  ToDoListCleanSwift/SceneDelegate.swift
  ToDoListCleanSwift/TasksScene/BL/Task.swift
  ToDoListCleanSwift/TasksScene/BL/TaskManager.swift
  ToDoListCleanSwift/TasksScene/Managers/OrderedTaskManager.swift
  ToDoListCleanSwift/TasksScene/Managers/Repository.swift
  ToDoListCleanSwift/TasksScene/Managers/SectionsAdapter.swift
  ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModels.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwift/TasksScene/TasksViewController.swift
  ToDoListCleanSwift/TasksScene/TasksWorker.swift
  ToDoListCleanSwift/TasksScene/View/CheckboxButton.swift
  ToDoListCleanSwift/TasksScene/View/TaskViewCell.swift
  ToDoListCleanSwiftTests/Managers/TaskManagerTests.swift
  ToDoListCleanSwiftTests/Tasks/ImportantTaskTests.swift
  ToDoListCleanSwiftTests/Tasks/RegularTaskTests.swift
Labels: enhancement

#9 Интеграция нового UI ячеек задач
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/CommonFiles/Extensions/UITableView+Extension.swift
  ToDoListCleanSwift/CommonFiles/Extensions/UIView+Extension.swift
  ToDoListCleanSwift/CommonFiles/Protocols/ConfigurableTableCell.swift
  ToDoListCleanSwift/TasksScene/BL/Task.swift
  ToDoListCleanSwift/TasksScene/BL/TaskManager.swift
  ToDoListCleanSwift/TasksScene/Cells/ImportantTaskTableViewCell.swift
  ToDoListCleanSwift/TasksScene/Cells/RegularTaskTableViewCell.swift
  ToDoListCleanSwift/TasksScene/Managers/Repository.swift
  ToDoListCleanSwift/TasksScene/Managers/SectionsAdapter.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwift/TasksScene/TasksViewController.swift
  ToDoListCleanSwift/TasksScene/View/CheckboxButton.swift
  ToDoListCleanSwift/TasksScene/View/TaskViewCell.swift
  ToDoListCleanSwiftTests/Managers/TaskManagerTests.swift
  ToDoListCleanSwiftTests/Tasks/RegularTaskTests.swift
Labels: enhancement

#19 Коррекция правил линтера
  .swiftlint.yml
  ToDoListCleanSwift/TasksScene/BL/Task.swift
  ToDoListCleanSwift/TasksScene/BL/TaskManager.swift
  ToDoListCleanSwift/TasksScene/Cells/ImportantTaskTableViewCell.swift
  ToDoListCleanSwift/TasksScene/Cells/RegularTaskTableViewCell.swift
  ToDoListCleanSwift/TasksScene/Managers/OrderedTaskManager.swift
  ToDoListCleanSwiftTests/Managers/TaskManagerTests.swift
  ToDoListCleanSwiftTests/Tasks/ImportantTaskTests.swift
Labels: bug

#15 Домашняя работа урока M2L2
  .gitignore
  .swiftlint.yml
  RULES.md
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/AppDelegate.swift
  ToDoListCleanSwift/Base.lproj/Main.storyboard
  ToDoListCleanSwift/CommonFiles/Extensions/UITableView+Extension.swift
  ToDoListCleanSwift/CommonFiles/Extensions/UIView+Extension.swift
  ToDoListCleanSwift/CommonFiles/Protocols/ConfigurableTableCell.swift
  ToDoListCleanSwift/LoginScene/LoginInteractor.swift
  ToDoListCleanSwift/LoginScene/LoginModels.swift
  ToDoListCleanSwift/LoginScene/LoginPresenter.swift
  ToDoListCleanSwift/LoginScene/LoginViewController.swift
  ToDoListCleanSwift/LoginScene/LoginWorker.swift
  ToDoListCleanSwift/MainRouter.swift
  ToDoListCleanSwift/SceneDelegate.swift
  ToDoListCleanSwift/TasksScene/BL/Task.swift
  ToDoListCleanSwift/TasksScene/BL/TaskManager.swift
  ToDoListCleanSwift/TasksScene/Cells/ImportantTaskTableViewCell.swift
  ToDoListCleanSwift/TasksScene/Cells/RegularTaskTableViewCell.swift
  ToDoListCleanSwift/TasksScene/Managers/OrderedTaskManager.swift
  ToDoListCleanSwift/TasksScene/Managers/Repository.swift
  ToDoListCleanSwift/TasksScene/Managers/SectionsAdapter.swift
  ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwift/TasksScene/TasksViewController.swift
  ToDoListCleanSwift/TasksScene/TasksWorker.swift
  ToDoListCleanSwift/TasksScene/View/CheckboxButton.swift
  ToDoListCleanSwift/TasksScene/View/TaskViewCell.swift
  ToDoListCleanSwiftTests/Managers/TaskManagerTests.swift
  ToDoListCleanSwiftTests/Tasks/ImportantTaskTests.swift
  ToDoListCleanSwiftTests/Tasks/RegularTaskTests.swift
Labels: merging to main

#22 Добавление пакета ToDoListBusinessLogic
  ToDoListBusinessLogic/.swiftpm/xcode/package.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ToDoListBusinessLogic/.swiftpm/xcode/xcshareddata/xcschemes/ToDoListBusinessLogic.xcscheme
  ToDoListBusinessLogic/.swiftpm/xcode/xcshareddata/xcschemes/ToDoListBusinessLogicTests.xcscheme
  ToDoListBusinessLogic/Package.swift
  ToDoListBusinessLogic/README.md
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/OrderedTaskManager.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/Task.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/TaskManager.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/ImportantTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/RegularTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/TaskManagerTests.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwift.xcscheme
  ToDoListCleanSwift.xcodeproj/xcuserdata/evgenimeleshin.xcuserdatad/xcschemes/xcschememanagement.plist
  ToDoListCleanSwift/TasksScene/Managers/Repository.swift
  ToDoListCleanSwift/TasksScene/Managers/SectionsAdapter.swift
  ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwift/TasksScene/TasksWorker.swift
Labels: enhancement

#29 Добавлены тесты для SectionAdapter
  ToDoListBusinessLogic/Package.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/OrderedTaskManager.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/Task.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/TaskManager.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/ImportantTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/RegularTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/TaskManagerTests.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwiftTests.xcscheme
  ToDoListCleanSwiftTests/TestDoubles/TaskManagerSpy.swift
  ToDoListCleanSwiftTests/UnitTests/Managers/SectionAdapterTests.swift
Labels: enhancement

#33 Корректировка по замечаниям M2L2
  README.md
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/ImportantTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/RegularTaskTests.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
Labels: documentation, enhancement

#34 M2L3. Добавление теста для TasksWorker
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/TasksScene/Managers/SectionsAdapter.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksWorker.swift
  ToDoListCleanSwiftTests/UnitTests/Managers/SectionAdapterTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
Labels: enhancement

#36 M2L3. Добавить тесты для LoginWorker
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/LoginScene/LoginInteractor.swift
  ToDoListCleanSwift/LoginScene/LoginModels.swift
  ToDoListCleanSwift/LoginScene/LoginPresenter.swift
  ToDoListCleanSwift/LoginScene/LoginWorker.swift
  ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
Labels: enhancement

#38 Домашняя работа урока M2L3
  README.md
  ToDoListBusinessLogic/.swiftpm/xcode/package.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ToDoListBusinessLogic/.swiftpm/xcode/xcshareddata/xcschemes/ToDoListBusinessLogic.xcscheme
  ToDoListBusinessLogic/.swiftpm/xcode/xcshareddata/xcschemes/ToDoListBusinessLogicTests.xcscheme
  ToDoListBusinessLogic/Package.swift
  ToDoListBusinessLogic/README.md
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/OrderedTaskManager.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/Task.swift
  ToDoListBusinessLogic/Sources/ToDoListBusinessLogic/TaskManager.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/TestDoubles/TaskManagerSpy.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/UnitTests/ImportantTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/UnitTests/OrderedTaskManagerTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/UnitTests/RegularTaskTests.swift
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/UnitTests/TaskManagerTests.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwift.xcscheme
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwiftTests.xcscheme
  ToDoListCleanSwift.xcodeproj/xcuserdata/evgenimeleshin.xcuserdatad/xcschemes/xcschememanagement.plist
  ToDoListCleanSwift/LoginScene/LoginInteractor.swift
  ToDoListCleanSwift/LoginScene/LoginModels.swift
  ToDoListCleanSwift/LoginScene/LoginPresenter.swift
  ToDoListCleanSwift/LoginScene/LoginWorker.swift
  ToDoListCleanSwift/TasksScene/BL/TaskManager.swift
  ToDoListCleanSwift/TasksScene/Managers/OrderedTaskManager.swift
  ToDoListCleanSwift/TasksScene/Managers/Repository.swift
  ToDoListCleanSwift/TasksScene/Managers/SectionsAdapter.swift
  ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwift/TasksScene/TasksWorker.swift
  ToDoListCleanSwiftTests/Managers/TaskManagerTests.swift
  ToDoListCleanSwiftTests/RepositoryTests.swift
  ToDoListCleanSwiftTests/Tasks/ImportantTaskTests.swift
  ToDoListCleanSwiftTests/TestDoubles/TaskManagerSpy.swift
  ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
  ToDoListCleanSwiftTests/UnitTests/Managers/SectionAdapterTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
Labels: merging to main

#46 M2L4. Добавлены тесты на LoginInteractor
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/TestDoubles/TaskManagerSpy.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/LoginScene/LoginInteractor.swift
  ToDoListCleanSwiftTests/TestDoubles/LoginPresenterSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/LoginWorkerSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/TaskManagerSpy.swift
  ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginInteractorTests.swift
Labels: enhancement

#45 M2L4. Добавление тестов для TasksInteractor
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
  ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/SectionAdapterSpy.swift
  ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TasksPresenerSpy.swift
  ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TestsWorkerSpy.swift
  ToDoListCleanSwiftTests/TasksScene/TasksWorkerTests.swift
Labels: enhancement

#48 M2L4. Добавлены тесты на TasksPresenter
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwift.xcscheme
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwiftTests.xcscheme
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwiftTests/TasksScene/TasksPresenterTests.swift
  ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/SectionAdapterSpy.swift
  ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TasksViewControllerSpy.swift
  ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TestsWorkerSpy.swift
Labels: enhancement

#49 M2L4. Добавление тестов для TaskViewController
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwiftTests/TestDoubles/TasksInteractorSpy.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/TasksViewControllerTests.swift
Labels: enhancement

#53 Домашняя работа урока M2L4
  ToDoListBusinessLogic/Tests/ToDoListBusinessLogicTests/TestDoubles/TaskManagerSpy.swift
  ToDoListCleanSwift.xcodeproj/project.pbxproj
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwift.xcscheme
  ToDoListCleanSwift.xcodeproj/xcshareddata/xcschemes/ToDoListCleanSwiftTests.xcscheme
  ToDoListCleanSwift/LoginScene/LoginInteractor.swift
  ToDoListCleanSwift/LoginScene/LoginPresenter.swift
  ToDoListCleanSwift/TasksScene/TasksInteractor.swift
  ToDoListCleanSwift/TasksScene/TasksModel.swift
  ToDoListCleanSwift/TasksScene/TasksPresenter.swift
  ToDoListCleanSwiftTests/TestDoubles/LoginPresenterSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/LoginViewControllerSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/LoginWorkerSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/SectionAdapterSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/TaskManagerSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/TasksInteractorSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/TasksPresenerSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/TasksViewControllerSpy.swift
  ToDoListCleanSwiftTests/TestDoubles/TesksWorkerSpy.swift
  ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginInteractorTests.swift
  ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginPresenterTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/Managers/RepositoryTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/Managers/SectionAdapterTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/TasksInteractorTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/TasksPresenterTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/TasksViewControllerTests.swift
  ToDoListCleanSwiftTests/UnitTests/TasksScene/TasksWorkerTests.swift
Labels: merging to main

#51 M2L5. Добавление PinLayout в проект
  README.md
  ToDoListCleanSwift.xcodeproj/project.pbxproj
Labels: enhancement
